In [2]:
import numpy as np

In [3]:
#Creating a numpy array

In [4]:
my_list = [1,2,3]

In [5]:
x = np.array(my_list)

In [6]:
type(x)

numpy.ndarray

In [7]:
my_matrix= [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [10]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [13]:
np.zeros((3,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [14]:
np.ones(4)

array([ 1.,  1.,  1.,  1.])

In [15]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [16]:
np.linspace(0,10,30)

array([  0.        ,   0.34482759,   0.68965517,   1.03448276,
         1.37931034,   1.72413793,   2.06896552,   2.4137931 ,
         2.75862069,   3.10344828,   3.44827586,   3.79310345,
         4.13793103,   4.48275862,   4.82758621,   5.17241379,
         5.51724138,   5.86206897,   6.20689655,   6.55172414,
         6.89655172,   7.24137931,   7.5862069 ,   7.93103448,
         8.27586207,   8.62068966,   8.96551724,   9.31034483,
         9.65517241,  10.        ])

In [17]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [21]:
np.random.rand(5,4)

array([[ 0.74451694,  0.32431123,  0.67119372,  0.40299928],
       [ 0.40458756,  0.68717712,  0.96459409,  0.18415169],
       [ 0.75807214,  0.69731191,  0.14444106,  0.88724634],
       [ 0.0231032 ,  0.18253806,  0.43728162,  0.98827685],
       [ 0.49066596,  0.12871758,  0.52758208,  0.63452442]])

In [23]:
np.random.randn(5, 4)

array([[-0.98480459,  2.56985538, -0.56249509,  0.11878677],
       [ 0.06982846,  0.649889  ,  0.75250853,  1.1641637 ],
       [-0.56349421,  1.4417143 ,  1.21009131, -1.65909994],
       [ 0.82598946, -1.71183691, -0.48666069, -0.66724777],
       [ 0.02697626, -0.54039463, -0.36928947, -1.08681417]])

In [26]:
np.random.randint(1,100,(3,2))

array([[56, 26],
       [34, 53],
       [38,  1]])

In [27]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [29]:
ranarr

array([31,  0, 11, 21,  8, 31, 33, 48, 19, 35])

In [30]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
arr.shape

(25,)

In [32]:
arr.dtype

dtype('int64')